### ISSUE TITLE
All shares being rejected (0.4)

### ISSUE THREAD

**Issue by liberza** [wolf9466/wolf-xmr-miner#17]
Running the 0.4 release, all shares seem to be getting rejected from moneropool.com because of low difficulty. Using the same xmr.conf on 0.3 results in all shares being accepted and ~10H/s more hashrate. I'm on Hawaii, with 6 threads on CPU as well.

Update: Disabling CPU mining does not fix the issue.
Update 2: Disabled GPU mining, shares seem to be getting accepted with CPU mining only.

**Comment by ZeroASIC** [comment]
can you post the config?

**Comment by ZeroASIC** [comment]
Actually, turn it down to on thread per GPU first!

**Comment by liberza** [comment]
Already was at one thread / GPU. Here's the config.

```
{
    "Algorithms":
    [
        {
            "name": "CryptoNight",
            "devices":
            [
                {
                    "index": 0,
                    "corefreq": 650,
                    "memfreq": 1250,
                    "fanspeed": 70,
                    "powertune": 20,
                    "threads": 1,
                    "rawintensity": 1250,
                    "worksize": 8
                },
                {
                    "index": -1,
                    "threads": 6,
                    "rawintensity": 32,
                    "worksize": 8
                }
            ],
            "pools":
            [
                {
                ...
                }
            ]
        }
    ]
}
```

**Comment by ZeroASIC** [comment]
Ok it's probably not the config. Just as a note though; corefreq, memfreq, fanspeed, and powertune don't do anything.

I'm running Ubuntu 16.04 with the newest AMD drivers manually installed and I compiled it myself. Works like a charm for me!

**Comment by liberza** [comment]
They don't do anything for both CPU and GPU mining?

I'm on an older version of Ubuntu with potentially old drivers. I'll try newer drivers and report back.

**Comment by liberza** [comment]
Upgraded from Ubuntu 14.04 to 16.04, removed fglrx and installed amdgpu drivers. Shares are now getting accepted.
