### ISSUE TITLE
AMD M600 mobile card on Dell M6700 running 64bit Arch Linux

### ISSUE THREAD

**Issue by potyt** [wolf9466/wolf-xmr-miner#3]
Managed to clone and compile fine - good start!

Unfortunately, miner executable is core dumping, not sure how to get any further.... have attached as much info as possible here.

When I run I get the following:

    xxx@xxx:~|⇒  ./miner xmr.conf

    [14:27:38] Parsed pool URL: monerohash.com
    [14:27:38] Successfully connected to pool's stratum.
    [14:27:38] Request: {"method": "login", "params": {"login": "XXXXX", "pass": "x", "agent": "miner/0.1"}, "id": 1}

    [14:27:38] Got something: {"id":1,"jsonrpc":"2.0","error":null,"result":{"id":"821036645537242","job":{"blob":"0102d9d4c9b405c0a4fa890a5237a63b24b1691883b2b60da753bd4143e43e997fc96b94bf34860000000018f197153946d0ce6eb9681523e50cbc00c48e7f6158a5cd9233dbbe8bf62aad01","job_id":"781557749793864","target":"711b0d00"},"status":"OK"}}

    [1]    2030 segmentation fault (core dumped)  miner xmr.conf

xmr.conf:

    {
	  "Algorithms":
	  [
		  {
			  "name": "CryptoNight",
			  "devices":
			  [
				  {
					  "index": 0,
					  "corefreq": 750,
					  "memfreq": 4500,
					  "fanspeed": 65,
					  "powertune": 20,
					  "threads": 2,
					  "rawintensity": 1024,
					  "worksize": 16
				  }
			  ],
			  "pools":
			  [
				  {
					  "url": "stratum+tcp://monerohash.com:3333",
					  "user": "XXXXXX",
					  "pass": "x"
				  }
			  ]
		  }
	  ]
    }

Running on an up to date Arch linux system. If I run /opt/AMDAPP/SDK/bin/clinfo, I can get the following info about my cards:

    xxx@xxx:~|⇒  cat /tmp/clinfo.txt

    Number of platforms:				 1
      Platform Profile:				 FULL_PROFILE
      Platform Version:				 OpenCL 1.1 MESA 11.1.0
      Platform Name:				 Clover
      Platform Vendor:				 Mesa
      Platform Extensions:				 cl_khr_icd
      Platform Name:				 Clover
    Number of devices:				 1
      Device Type:					 CL_DEVICE_TYPE_GPU
      Vendor ID:					 1002h
      Max compute units:				 10
      Max work items dimensions:			 3
        Max work items[0]:				 256
        Max work items[1]:				 256
        Max work items[2]:				 256
      Max work group size:				 256
      Preferred vector width char:			 16
      Preferred vector width short:			 8
      Preferred vector width int:			 4
      Preferred vector width long:			 2
      Preferred vector width float:			 4
      Preferred vector width double:		 2
      Native vector width char:			 16
      Native vector width short:			 8
      Native vector width int:			 4
      Native vector width long:			 2
      Native vector width float:			 4
      Native vector width double:			 2
      Max clock frequency:				 800Mhz
      Address bits:					 32
      Max memory allocation:			 268435456
      Image support:				 No
      Max size of kernel argument:			 1024
      Alignment (bits) of base address:		 1024
      Minimum alignment (bytes) for any datatype:	 128
      Single precision floating point capability
        Denorms:					 No
        Quiet NaNs:					 Yes
        Round to nearest even:			 Yes
        Round to zero:				 No
        Round to +ve and infinity:			 No
        IEEE754-2008 fused multiply-add:		 No
      Cache type:					 None
      Cache line size:				 0
      Cache size:					 0
      Global memory size:				 1073741824
      Constant buffer size:				 268435456
      Max number of constant args:			 16
      Local memory type:				 Scratchpad
      Local memory size:				 32768
      Kernel Preferred work group size multiple:	 64
      Error correction support:			 0
      Unified memory for Host and Device:		 1
      Profiling timer resolution:			 0
      Device endianess:				 Little
      Available:					 Yes
      Compiler available:				 Yes
      Execution capabilities:				 
        Execute OpenCL kernels:			 Yes
        Execute native function:			 No
      Queue on Host properties:				 
        Out-of-Order:				 No
        Profiling :					 Yes
      Platform ID:					 0x7fddf08f5a60
      Name:						 AMD CAPE VERDE (DRM 2.43.0, LLVM 3.7.0)
      Vendor:					 AMD
      Device OpenCL C version:			 OpenCL C 1.1 
      Driver version:				 11.1.0
      Profile:					 FULL_PROFILE
      Version:					 OpenCL 1.1 MESA 11.1.0
      Extensions:					 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_fp64

Any ideas of what I am doing wrong, or what I can do to provide some useful info to you to fix this?

**Comment by wolf9466** [comment]
You're using the OSS drivers, which won't work with this, as it uses things Catalyst supports - sorry.
