### ISSUE TITLE
Error -11 when calling clBuildProgram

### ISSUE THREAD

**Issue by kpstolk** [wolf9466/wolf-xmr-miner#4]
Thanks for developing an open source miner :)
I can't get it to work though, first got the clCreateBuffer error, lowered the rawintensity. Now with a lower rawintensity it crashes, begin error log from command line:

> [23:04:58] Parsed pool URL: address.pool.to
> [23:04:59] Successfully connected to pool's stratum.
> [23:04:59] Request: {"method": "login", "params": {"login": "address", "pass": "x", "agent": "wolf-xmr-miner/0.1"}, "id": 1}
> 
> [23:05:00] Got something: {"id":1,"jsonrpc":"2.0","error":null,"result":{"id":"726771638076752","job":{"blob":"0203bfc9d7ba05822301aaa8470bee8395a5881cb514788d3d9a4ead804e686253bc64a14eb33400000000c3e09e9a82595af22b18dea4c1300e2681542510e174f0016f520ff5e62dbfbf01","job_id":"759011925593949","target":"169f0200"},"status":"OK"}}
> 
> [23:05:00] Error -11 when calling clBuildProgram.
> [23:05:00] Build Log:
> "C:\Users\myuser\AppData\Local\Temp\jh.cl", line 102: error: identifier
>           "sph_u64" is undefined
>   __constant static const sph_u64 C[] = {
>                           ^
> 
> "C:\Users\myuser\AppData\Local\Temp\jh.cl", line 103: error: identifier
>           "SPH_C64" is undefined
>     C64e(0x72d5dea2df15f867), C64e(0x7b84150ab7231557),
>     ^
> 
> "C:\Users\myuser\AppData\Local\Temp\jh.cl", line 103: error: function call is
>           not allowed in a constant expression
>     C64e(0x72d5dea2df15f867), C64e(0x7b84150ab7231557),
>     ^

Using version wolf-xmr-miner-0.2 on Windows 10 Pro.
GPUs: 2x AMD Radeon HD 7900 Series GPU Tahiti
Driver: 9.14.10.01197, Crimson 16.5.3

[wolf-xmr-miner-0.2-crash.txt](https://github.com/wolf9466/wolf-xmr-miner/files/301345/wolf-xmr-miner-0.2-crash.txt)

**Comment by anazhd** [comment]
I'm too having this problem out of nowhere. Was working fine before, no driver changes or updates whatsoever. I'm using quite decent gpu. Still unable to find a fix.

**Comment by TheXev** [comment]
This solution worked for me! Thank you so much!  Deleting the temp files made the CL compiler work correctly.

**Comment by wolf9466** [comment]
I believe this to be resolved, then.
