### ISSUE TITLE
Error -1 when calling clGetDeviceIDs for number of devices.

### ISSUE THREAD

**Issue by avnr** [wolf9466/wolf-xmr-miner#6]
GPU is AMD Radeon HD 5800 Series 1GB RAM.
Catalyst version 15.7.1 on Win7 Ent.
The machine has another onboard Intel GPU, with BFGMiner I select the AMD device as 1:0 and it works fine.
The problem persists with both miner versions 0.2 and 0.3b.

Can you help?
Thx

**Comment by wolf9466** [comment]
There's no GPU's supporting OpenCL recognized, or (more likely) you're not selecting the correct platform.

**Comment by avnr** [comment]
But how does one select the right platform? I couldn't find a clue in neither the README nor the conf file.

**Comment by wolf9466** [comment]
Actually, this is a good point - I'm going to open a new issue for this, as currently there is to way to tell it besides modifying the code.

**Comment by bpvarsity** [comment]
I am seeing the same error. All my other mining programs see my gpu's. I cant find anything in the readme about how to fix this or list the gpu's.
